# Generated by Django 5.2.12 on 2026-04-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_state', models.CharField(default='unknown', max_length=20)),
                ('yawn_detected', models.BooleanField(default=False)),
                ('head_alert', models.BooleanField(default=False)),
                ('driver_status', models.CharField(default='normal', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='trips.trip')),
            ],
        ),
    ]
